#ifndef __core_config_h
	#define __core_config_h  1
	#define	core_config_cir_identity	0x00000053
	#define	core_config_cir_identity_chipid	0
	#define	core_config_cir_identity_arcnum	0
	#define	core_config_cir_identity_arcver	83
	#define	core_config_cir_identity_family	5
	#define	core_config_cir_identity_corever	3
	#define	core_config_cir_aux_volatile	0xc0000002
	#define	core_config_cir_aux_volatile_base_region	12
	#define	core_config_cir_aux_volatile_limit_region	0
	#define	core_config_cir_aux_volatile_s	1
	#define	core_config_cir_aux_volatile_d	0
	#define	core_config_bcr_bcr_ver	0x00000002
	#define	core_config_bcr_bcr_ver_version	2
	#define	core_config_bcr_vecbase_ac_build	0x80000010
	#define	core_config_bcr_rf_build	0x00000102
	#define	core_config_bcr_rf_build_version	2
	#define	core_config_bcr_rf_build_p	1
	#define	core_config_bcr_rf_build_e	0
	#define	core_config_bcr_rf_build_r	0
	#define	core_config_bcr_rf_build_b	0
	#define	core_config_bcr_rf_build_d	0
	#define	core_config_bcr_mmu_build	0x04e2094a
	#define	core_config_bcr_mmu_build_version	4
	#define	core_config_bcr_mmu_build_sl	1
	#define	core_config_bcr_mmu_build_psz1	12
	#define	core_config_bcr_mmu_build_psz0	4
	#define	core_config_bcr_mmu_build_pae	0
	#define	core_config_bcr_mmu_build_ja	2
	#define	core_config_bcr_mmu_build_je	1
	#define	core_config_bcr_mmu_build_jes	1
	#define	core_config_bcr_mmu_build_itlb	1
	#define	core_config_bcr_mmu_build_dtlb	2
	#define	core_config_bcr_d_cache_build	0x10226105
	#define	core_config_bcr_d_cache_build_version	5
	#define	core_config_bcr_d_cache_build_assoc	1
	#define	core_config_bcr_d_cache_build_capacity	6
	#define	core_config_bcr_d_cache_build_bsize	2
	#define	core_config_bcr_d_cache_build_fl	2
	#define	core_config_bcr_d_cache_build_ioc	0
	#define	core_config_bcr_d_cache_build_cp	0
	#define	core_config_bcr_d_cache_build_u	0
	#define	core_config_bcr_d_cache_build_cycles	2
	#define	core_config_bcr_timer_build	0x00000304
	#define	core_config_bcr_timer_build_sp1	0
	#define	core_config_bcr_timer_build_sp0	0
	#define	core_config_bcr_timer_build_p1	0
	#define	core_config_bcr_timer_build_p0	0
	#define	core_config_bcr_timer_build_st1	0
	#define	core_config_bcr_timer_build_st0	0
	#define	core_config_bcr_timer_build_rtc	0
	#define	core_config_bcr_timer_build_rtsc_ver	0
	#define	core_config_bcr_timer_build_rtsc	0
	#define	core_config_bcr_timer_build_t0	1
	#define	core_config_bcr_timer_build_t1	1
	#define	core_config_bcr_timer_build_version	4
	#define	core_config_bcr_ap_build	0x00000605
	#define	core_config_bcr_ap_build_version	5
	#define	core_config_bcr_ap_build_type	6
	#define	core_config_bcr_i_cache_build	0x00236204
	#define	core_config_bcr_i_cache_build_assoc	2
	#define	core_config_bcr_i_cache_build_version	4
	#define	core_config_bcr_i_cache_build_capacity	6
	#define	core_config_bcr_i_cache_build_bsize	3
	#define	core_config_bcr_i_cache_build_fl	2
	#define	core_config_bcr_i_cache_build_d	0
	#define	core_config_bcr_multiply_build	0x00023206
	#define	core_config_bcr_multiply_build_version16x16	2
	#define	core_config_bcr_multiply_build_dsp	3
	#define	core_config_bcr_multiply_build_cyc	0
	#define	core_config_bcr_multiply_build_type	2
	#define	core_config_bcr_multiply_build_version32x32	6
	#define	core_config_bcr_swap_build	0x00000003
	#define	core_config_bcr_swap_build_version	3
	#define	core_config_bcr_norm_build	0x00000003
	#define	core_config_bcr_norm_build_version	3
	#define	core_config_bcr_minmax_build	0x00000002
	#define	core_config_bcr_minmax_build_version	2
	#define	core_config_bcr_barrel_build	0x00000303
	#define	core_config_bcr_barrel_build_version	3
	#define	core_config_bcr_barrel_build_shift_option	3
	#define	core_config_bcr_bpu_build	0x01a91105
	#define	core_config_bcr_bpu_build_version	5
	#define	core_config_bcr_bpu_build_bce	1
	#define	core_config_bcr_bpu_build_pte	2
	#define	core_config_bcr_bpu_build_rse	0
	#define	core_config_bcr_bpu_build_ft	1
	#define	core_config_bcr_bpu_build_ts	20
	#define	core_config_bcr_bpu_build_tqe	2
	#define	core_config_bcr_bpu_build_fbe	1
	#define	core_config_bcr_isa_config	0x23e47402
	#define	core_config_bcr_isa_config_res1	0
	#define	core_config_bcr_isa_config_d	2
	#define	core_config_bcr_isa_config_res2	0
	#define	core_config_bcr_isa_config_f	0
	#define	core_config_bcr_isa_config_c	3
	#define	core_config_bcr_isa_config_l	1
	#define	core_config_bcr_isa_config_n	1
	#define	core_config_bcr_isa_config_a	1
	#define	core_config_bcr_isa_config_b	0
	#define	core_config_bcr_isa_config_addr_size	4
	#define	core_config_bcr_isa_config_lpc_size	7
	#define	core_config_bcr_isa_config_pc_size	4
	#define	core_config_bcr_isa_config_version	2
	#define	core_config_bcr_cluster_build	0x00000101
	#define	core_config_bcr_cluster_build_per	0
	#define	core_config_bcr_cluster_build_c	0
	#define	core_config_bcr_cluster_build_num_entries	0
	#define	core_config_bcr_cluster_build_num_cores	1
	#define	core_config_bcr_cluster_build_version	1
	#define	core_config_bcr_irq_build	0x011b2001
	#define	core_config_bcr_irq_build_raz	0
	#define	core_config_bcr_irq_build_f	0
	#define	core_config_bcr_irq_build_p	1
	#define	core_config_bcr_irq_build_exts	27
	#define	core_config_bcr_irq_build_irqs	32
	#define	core_config_bcr_irq_build_version	1
	#define	core_config_bcr_pct_build	0x00080503
	#define	core_config_bcr_pct_build_version	3
	#define	core_config_bcr_pct_build_s	1
	#define	core_config_bcr_pct_build_i	1
	#define	core_config_bcr_pct_build_c	8
	#define	core_config_bcr_cc_build	0x00790002
	#define	core_config_bcr_cc_build_version	2
	#define	core_config_bcr_cc_build_cc	121
	#define	core_config_bcr_isa_profile	0x00011101
	#define	core_config_bcr_isa_profile_g3	1
	#define	core_config_bcr_isa_profile_g2	1
	#define	core_config_bcr_isa_profile_g1	1
	#define	core_config_bcr_isa_profile_version	1
	#define	core_config_family	5
	#define	core_config_core_version	3
	#define	core_config_family_name	"arcv2hs"
	#define	core_config_code_density	1
	#define	core_config_rgf_num_banks	1
	#define	core_config_rgf_num_wr_ports	2
	#define	core_config_endian	"little"
	#define	core_config_endian_little	1
	#define	core_config_endian_big	0
	#define	core_config_lpc_size	32
	#define	core_config_pc_size	32
	#define	core_config_addr_size	32
	#define	core_config_atomic	1
	#define	core_config_ll64	1
	#define	core_config_unaligned	1
	#define	core_config_div_rem	"radix4"
	#define	core_config_div_rem_radix4	1
	#define	core_config_swap	1
	#define	core_config_bitscan	1
	#define	core_config_mpy_option	"qmpyh"
	#define	core_config_mpy_option_num	9
	#define	core_config_shift_assist	1
	#define	core_config_barrel_shifter	1
	#define	core_config_timer0	1
	#define	core_config_timer0_level	0
	#define	core_config_timer0_vector	16
	#define	core_config_timer1	1
	#define	core_config_timer1_level	0
	#define	core_config_timer1_vector	17
	#define	core_config_action_points	8
	#define	core_config_bpu_bc_entries	512
	#define	core_config_bpu_pt_entries	8192
	#define	core_config_bpu_rs_entries	4
	#define	core_config_bpu_bc_full_tag	1
	#define	core_config_bpu_bc_tag_size	20
	#define	core_config_bpu_tosq_entries	5
	#define	core_config_bpu_fb_entries	2
	#define	core_config_mmuv4_present	1
	#define	core_config_mmuv4	1
	#define	core_config_mmu_pgsz	8192
	#define	core_config_mmu_pgsz_KM	"8K"
	#define	core_config_mmu_ntlb_entries	512
	#define	core_config_mmu_stlb_entries	16
	#define	core_config_mmu_super_pgsz	2097152
	#define	core_config_mmu_super_pgsz_KM	"2M"
	#define	core_config_interrupts_present	1
	#define	core_config_interrupts_number	32
	#define	core_config_interrupts_priorities	2
	#define	core_config_interrupts_externals	27
	#define	core_config_interrupts	32
	#define	core_config_interrupt_priorities	2
	#define	core_config_ext_interrupts	27
	#define	core_config_interrupts_base	0x80000000
	#define	core_config_dcache_present	1
	#define	core_config_dcache_size	32768
	#define	core_config_dcache_line_size	64
	#define	core_config_dcache_ways	2
	#define	core_config_dcache_feature	2
	#define	core_config_dcache_mem_cycles	2
	#define	core_config_icache_present	1
	#define	core_config_icache_size	32768
	#define	core_config_icache_line_size	64
	#define	core_config_icache_ways	4
	#define	core_config_icache_feature	2
	#define	core_config_pct_counters	8
	#define	core_config_pct_interrupt	1
	#define	core_config_clock_speed	200
#endif /* __core_config_h */